Upgrade from Node 8 to 12 (#71)
Imagery had to be held back to Node 10, as the gphoto2 bindings
do not compile under Node 12:

../src/camera.cc: In static member function 'static void GPCamera::Initialize(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)':
../src/camera.cc:43:38: error: no matching function for call to 'v8::FunctionTemplate::GetFunction()'
   43 |   constructor.Reset(tpl->GetFunction());